### ISSUE TITLE
Examples don't work, no links..

### ISSUE THREAD

**Issue by MGParisi** [kreait/firebase-tokens-php#10]
Maybe provide links to the Firebase SDK?

Also, the examples on the main page fail.  How do we make them work?

**Comment by jeromegamez** [comment]
Thanks for the hints, I added a link to the Firebase PHP SDK and (hopefully) reduced the ambiguity of the examples with b5bcfb18b8ee9688836e21b479805977aafe5d47 . As we discussed this and other points in https://github.com/kreait/firebase-php/issues/170 and in the Firebase Community Slack, I will close this issue now, but feel free to add further comments.

For others stumbling over this: I responded to this and other pain points in https://github.com/kreait/firebase-php/issues/170#issuecomment-368174830
