### ISSUE TITLE
Do you really need to force developers to install Composer?

### ISSUE THREAD

**Issue by andreszs** [kreait/firebase-tokens-php#11]
Is it so hard to type` include('domain/generator.php')` and so on to include the required files, that you force developers to install the **Composer** extension to save a few bytes?

Honestly I never understood that policy of adding unnecessary extensions that only create problems when trying to setup a new server or migrate an existing one. Please reconsider it in your future projects if you want to make them ready to use without headaches and complications for fellow developers, thanks.

**Comment by jeromegamez** [comment]
Considering that you are using Composer and npm in your own GitHub projects, I am sure I don't have to explain the benefits of dependency management tools to you.

However, as this library is open source and has a permissive license, feel free to fork or copy it and change it to your likings.
