### ISSUE TITLE
Tag release with Guzzle 7 support

### ISSUE THREAD

**Issue by dwightwatson** [kreait/firebase-tokens-php#28]
It looks like `composer.json` was updated for Guzzle 7 stable, but a new release hasn't been tagged.

Laravel 8 now requires Guzzle 7.0 so this prevents it from being installed alongside. 

Could we please get a new tagged release?

**Comment by jeromegamez** [comment]
The current release already support Guzzle 7 (starting with beta, including stable), see https://github.com/kreait/firebase-tokens-php/blob/1.10.0/composer.json#L19 

Perhaps related: https://github.com/kreait/laravel-firebase/issues/59

**Comment by dwightwatson** [comment]
Ah yeah, my bad. Misunderstood what I was seeing. Thanks for the quick & helpful response (as well as a great library)!

**Comment by jeromegamez** [comment]
No problem, I often get outdated dependencies and am in the same situation 😅. Thank you for your kind words, that always makes me happy 🌺
