### ISSUE TITLE
How to clear cache?

### ISSUE THREAD

**Issue by produktive** [kreait/firebase-tokens-php#29]
> Cache results from the Google Secure Token Store

> In order to verify ID tokens, the verifier makes a call to fetch Firebase's currently available public keys.
> The keys are cached in memory by default.

How do I clear this cache? I created a new project and it is still looking for the old project name.

**Comment by jeromegamez** [comment]
The InMemory Cache is cleared after a script/request is terminated. If you're using another kind of cache provided by another library, you need to look up in their docs how to clear the cache.

I'm not sure what you mean, though: only the public keys from Google are cached, and these are not tied to a Firebase project or a project's name 🤔

**Comment by produktive** [comment]
Hmm, then I'm not sure what type of problem I'm experiencing. I had this working a few days ago. I deleted my old Firebase project (ccamd-fish-tracker) and created a new one (cca-md). Since then, I'm getting this error:
PHP message: attempt to error The value 'eyJhbGciOiJSUzI...' is not a verified ID token:
- The token's audience doesn't match the current Firebase project. Expected 'ccamd-fish-tracker', got 'cca-md'.
- The token was issued by the wrong principal. Expected 'https://securetoken.google.com/ccamd-fish-tracker', got 'https://securetoken.google.com/cca-md'

This is my verify function:
```
function verify($tokenid) {
	if (isset($tokenid)) {

		$projectId = 'cca-md'; // cca-md
		$idToken = $tokenid; // An ID token given to your backend by a Client application

		$verifier = IdTokenVerifier::createWithProjectId($projectId);

		try {
		    $token = $verifier->verifyIdToken($idToken);
		} catch (IdTokenVerificationFailed $e) {
		    $data = $e->getMessage();
			$token = null;
		}

		try {
		    $token = $verifier->verifyIdTokenWithLeeway($idToken, $leewayInSeconds = 300);
		} catch (IdTokenVerificationFailed $e) {
		    $data = $e->getMessage();
			$token = null;
		}
	} else {
		$token = null;
	}
	return $token;
}
```

I'm not sure where it's still getting my old project name from?

**Comment by produktive** [comment]
Wow I'm an idiot. I found the problem, it was using the wrong project name is a different file. Sorry for the bother.

**Comment by jeromegamez** [comment]
No problem, I was just about to suggest the same, and you saved me from writing it 😅. Glad you came to the solution yourself, it's always more satisfying this way 💪
