### ISSUE TITLE
php8 compat

### ISSUE THREAD

**Issue by mitalcoi** [kreait/firebase-tokens-php#33]
Need to upgrade dependencies to lcobucci/jwt:^4.0, otherwise library can be incompatible with php 8

**Comment by jeromegamez** [comment]
It needs more than just that, I'm working on it as we speak 🤞

**Comment by jeromegamez** [comment]
Implemented with 1e8fb135a577b36bd1e88ef37c0301d1d3f13c9d, released with [1.13.0](https://github.com/kreait/firebase-tokens-php/releases/tag/1.13.0) 🚀
