### ISSUE TITLE
'Lcobucci\JWT\Signer\Key\InMemory' not found

### ISSUE THREAD

**Issue by yacineblr** [kreait/firebase-tokens-php#38]
Hi, I just installed the lib with composer and I have a problem with the lib "Lcobucci/JWT".

Error:
```
Fatal error: Uncaught Error: Class 'Lcobucci\JWT\Signer\Key\InMemory' not found in /wp-content/plugins/myplugin/Firebase/vendor/kreait/firebase-tokens/src/Firebase/Auth/Token/Generator.php on line 38
```

My composer 
````json
    "minimum-stability": "dev",
    "require": {
        "kreait/firebase-php": "^5.19",
        "kreait/firebase-tokens": "^1.15"
    }
````

My php file
```php
  use Kreait\Firebase\Factory;
  use  Kreait\Firebase\Auth;
  
  $factory = (new Factory)->withServiceAccount(__DIR__ . '/google-service.json);
    
  $auth = $factory->createAuth();
```

Do you know what the error is, please ?

**Comment by jeromegamez** [comment]
The error indicates that a required class cannot be found (`Lcobucci\JWT\Signer\Key\InMemory`). This could have many reasons:

* The autoloader of your project didn't pick up the class, you can try to `composer dumpautoload` and see if that helps.
* If you're planning on using the SDK and not just the tokens library, you can remove the `kreait/firebase-tokens` dependency, as it is included in `kreait/firebase-php`
* It could be that other dependencies in your project prevent a working installation of the SDK

You can check what is installed by running `composer show` and see which version of the `kreait` and `lcobucci/jwt` libraries are installed. `lcobucci/jwt` should be a version greater than 3.4.1, `kreait/firebase-php` should currently be greater than 5.20.1 and `kreait/firebase-tokens` should be ^1.15.

I don't know how composer behaves in the context of a Wordpress project / Wordpress plugin (I've seen it in a file path of your original post), so I'm afraid I can't help with that.

**Comment by yacineblr** [comment]
Composer log after "composer installl":
```
  Problem 1
    - kreait/firebase-php[5.20.1, ..., 5.x-dev] require php ^7.4|^8.0 -> your php version (7.3.11) does not satisfy that requirement.
    - Root composer.json requires kreait/firebase-php ^5.20.1 -> satisfiable by kreait/firebase-php[5.20.1, 5.x-dev].
```

It was a problem with my PHP version (7.3.11) of "compose". It was installing "kreait/firebase-php" in version 5.19 and not the latest "5.20.1".

Thanks to the fact that you told me the version number, I solved the problem

**Comment by jeromegamez** [comment]
Glad that you came to a solution, and thank you for sharing it here - I'm sure others in a similar situation will benefit from it! 🙏
