### ISSUE TITLE
What is the purpose of HttpKeyStore.php

### ISSUE THREAD

**Issue by wcaaan** [kreait/firebase-tokens-php#39]
Hey, first of all great library, I used this library for developing a Laravel package for authenticating firebase token. would you be kind to tell me what is the purpose of HttpKeyStore.php ? thankyou

**Comment by jeromegamez** [comment]
The HttpKeyStore is where the public keys from Google are fetched - Firebase ID Tokens are signed with a private key by Google, and with the public keys we can verify that the signature is valid.

There are multiple private and public keys, they are identified by the `kid` header in the JWT.

I hope this helps!

**Comment by wcaaan** [comment]
Thank you. appreciate it,
