### ISSUE TITLE
Add support for verifySessionCookie

### ISSUE THREAD

**Issue by arma7x** [kreait/firebase-tokens-php#41]
1) Include **`https://session.firebase.google.com/{$this->projectId}`** to https://github.com/kreait/firebase-tokens-php/blob/main/src/JWT/Action/VerifyIdToken/WithLcobucciJWT.php#L71

2) Include **`https://www.googleapis.com/identitytoolkit/v3/relyingparty/publicKeys`** to https://github.com/kreait/firebase-tokens-php/blob/main/src/JWT/Action/FetchGooglePublicKeys.php#L12

**Comment by jeromegamez** [comment]
Implemented with #42 and https://github.com/kreait/firebase-tokens-php/commit/1ea0e3dc48a73202e050bb08a5a602e41dfd31b8, and released with https://github.com/kreait/firebase-tokens-php/releases/tag/2.1.0

(You don't need to create an issue _and_ a PR, on of both is enough 😅)
