### ISSUE TITLE
Version 4.2.0 of lcobucci/jwt breaks this package

### ISSUE THREAD

**Issue by jesperbjerke** [kreait/firebase-tokens-php#46]
After updating dependencies and getting a new peer-dependency of lcobucci/jwt my application started throwing "InvalidKeyProvided with message 'Key cannot be empty'" exception. After digging through the source code it seems to have been added on purpose, and then finding this: https://github.com/lcobucci/jwt/issues/877 confirms it. Which means this package needs to be updated accordingly I guess?

**Comment by jeromegamez** [comment]
Could you share the exception so that I can see where the error occurs here?

**Comment by jesperbjerke** [comment]
It's on `/vendor/kreait/firebase-tokens/src/Firebase/Auth/Token/Verifier.php(48): Lcobucci\\JWT\\Signer\\Key\\InMemory::plainText()`

They don't accept the empty string as argument to plainText() any longer.

**Comment by jeromegamez** [comment]
I get this error also, but only when running PHPStan. Is it a PHPStan error for you as well, or does it happen when you actually run the code?

**Comment by jesperbjerke** [comment]
I get it while running the application. Haven't tried running phpstan yet

**Comment by jeromegamez** [comment]
If it's not just PHPStan, how are you using the tokens library? Do you happen to pass an empty string?

I'm asking because the tokens library is used by kreait/firebase-php and I don't have this error there.

**Comment by jesperbjerke** [comment]
I'm using `kreait/laravel-firebase` although version 3.4.0. I can check if it's possible if we can upgrade to 4.x of laravel-firebase. But not sure since we're still running php 7.4 and have some other dependencies

**Comment by jeromegamez** [comment]
The 4.x release is compatible with PHP 7.4, but it uses release 6.x of the SDK (3.x uses 5.x of the SDK). If you are using the Laravel package as documented and without modifications It shouldn't cause you any problems.

But I will run the SDK's 5.x pipeline to make sure there's not a problem in there 🤞🏻

**Comment by jeromegamez** [comment]
I can confirm the problem occurs with version 1.x of the tokens library / version 5.x of the SDK.

I will try to implement a fix, but if it's possible for you to update to 4.x of the Laravel package, this might be a faster solution.

Thank you for reporting!

**Comment by jeromegamez** [comment]
I just published new releases for 1.x, 2.x and 3.x so I hope you'll be safe any way 😅. Thanks again!
