### ISSUE TITLE
ID token verification fails. 

### ISSUE THREAD

**Issue by egarro-sensopia** [kreait/firebase-tokens-php#6]
I think Google updated the 'iss' claim from https://securetoken.google.com/[projectId] to https://accounts.google.com. Therefore, verifyIdToken function fails with message: "This token has an invalid issuer". Am I doing something wrong?

**Comment by jeromegamez** [comment]
I just tested the library manually and it still works for me, the issuer has remained the same. Are you sure you have provided the method with an ID token string generated by a client SDK (see https://firebase.google.com/docs/auth/admin/verify-id-tokens)?

**Comment by egarro-sensopia** [comment]
Thank you for checking. Never mind, I forgot to exchange the AuthProvider idToken (google) for a Firebase idToken before sending to my backend (php) for verification. After using FIRUser getIDTokenForcingRefresh, I got a proper Firebase idToken that passes validation!
